name: test

on:
  push:
    branches: [ "main" ]

jobs:
  check-tests:
    runs-on: [self-hosted, linux, x64]
    outputs:
      tests-exist: ${{ steps.check-tests.outputs.tests-exist }}

    steps:
      - uses: actions/checkout@v3

      - name: Check for test scripts and create error log
        run: |
          if [ -f "test_vaja2.cpp" ]; then
            echo "Test scripts exist."
            echo "1" > napaka.txt
          else
            echo "Test scripts do not exist." >&2
            echo "0" > napaka.txt
          fi
        shell: bash

      - name: Upload error log
        uses: actions/upload-artifact@v2
        with:
          name: error-log
          path: napaka.txt

  run-tests:
    needs: check-tests
    runs-on: [self-hosted, linux, x64]
    strategy:
      matrix:
        gcc-version: [9, 10, 11]
    steps:
      - uses: actions/checkout@v3

      - name: Download error log
        uses: actions/download-artifact@v2
        with:
          name: error-log

      - name: Check error log content
        run: |
          content=$(cat napaka.txt)
          if [ "$content" == "0" ]; then
            echo "Error log indicates missing tests, stopping workflow."
            exit 1
          fi
        shell: bash

      - name: Install specific GCC version
        run: sudo apt-get update && sudo apt-get install -y g++-${{ matrix.gcc-version }}

      - name: Compile with the specified GCC version
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${{ matrix.gcc-version }} 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-${{ matrix.gcc-version }} 100
          gcc -v
          g++ -o test test_vaja2.cpp vaja2.cpp
          ./test
        shell: bash
