name: Deploy to DockerHub

# Sproži se takoj ko je "test" zaključen
on:
  workflow_run:
    workflows: ["test"]
    branches: [main]
    types:
      - completed

jobs:
  build-and-push:
    # Tu določim da je se izvaja na mojem okolju
    runs-on: [self-hosted, linux, x64]
    # Tu določim da se izvaja samo v primeru da je pri testu bil success
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # Preveri kodo na GitHubu
      - name: Checkout repository
        uses: actions/checkout@v3

      # Požene zapakiraj_27136.sh
      - name: Build and push Docker image
        run: ./zapakiraj_27136.sh
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
          IMAGE_NAME: "ci_cd"
          IMAGE_TAG: "latest"
