name: test

on:
  push:
    branches: [ "main" ]

jobs:
  check-tests:
    runs-on: [self-hosted, linux, x64]

    outputs:
      tests-exist: ${{ steps.check-tests.outputs.tests-exist }}

    steps:
      - uses: actions/checkout@v3

      - name: Check for test scripts
        id: check-tests
        run: |
          if [ -f "test_vaja2.cpp" ]; then
            echo "::set-output name=tests-exist::true"
            echo "Test scripts exist."
          else
            echo "Test scripts do not exist." >&2
            echo "::set-output name=tests-exist::false"
            echo "Test scripts are missing" > napaka.txt
            exit 1
          fi

      - name: Upload error log if tests are missing
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: error-log
          path: napaka.txt

  run-tests:
    needs: check-tests
    if: needs.check-tests.outputs.tests-exist == 'true'
    runs-on: [self-hosted, linux, x64]
    strategy:
      matrix:
        compiler: [gcc, clang]
        version: ["9", "10", "11"]
    steps:
      - uses: actions/checkout@v3

      - name: Install compiler
        run: |
          sudo apt-get update
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            sudo apt-get install -y g++-${{ matrix.version }}
          elif [ "${{ matrix.compiler }}" = "clang" ]; then
            sudo apt-get install -y clang-${{ matrix.version }}
          fi

      - name: Compile and run tests
        run: |
          ${{ matrix.compiler }} -v
          ${{ matrix.compiler }} -o test test_vaja2.cpp vaja2.cpp
          ./test
